### ISSUE TITLE
Don't know how to get DNS server IP

### ISSUE THREAD

**Issue by muthu329024** [awsdocs/aws-directory-service-admin-guide#11]
`For Conditional forwarder, type the IP address of your DNS server in the example.local forest (which you noted in the previous procedure).` 

There was no step which mentioned .. how to do this

**Comment by nicholaspierson** [comment]
Hi, if you look at the procedure just before the procedure you quoted if has this line which explains how to capture the DNS server address:

"Open Server Manager and in the console tree choose DNS. Take note of the IPv4 address listed for the server. You will need this in the next procedure when you create a conditional forwarder from corp.example.com to the example.local directory."
