### ISSUE TITLE
AWS Cloud Directory detail is missing

### ISSUE THREAD

**Issue by bcagarwal** [awsdocs/aws-directory-service-admin-guide#12]
On this link "https://docs.aws.amazon.com/directoryservice/latest/admin-guide/what_is.html" under "Which to Choose" table, "AWS Cloud Directory" is used to be listed as on option few days back. Now, it seems it has been removed though it is still listed on github.

Could you please clarify if AWS is no longer supporting AWS Cloud Directory and the details has intentionally been removed?

GitHub Link - https://github.com/awsdocs/aws-directory-service-admin-guide/blob/master/doc_source/what_is.md

Screenshots are attached as below

![Screen Shot 2020-07-09 at 9 50 45 PM](https://user-images.githubusercontent.com/20309135/87065160-50e9b880-c22e-11ea-8302-f4635c935216.png)
![Screen Shot 2020-07-09 at 9 49 52 PM](https://user-images.githubusercontent.com/20309135/87065172-53e4a900-c22e-11ea-88d8-2b6e482a185b.png)

**Comment by nicholaspierson** [comment]
Hi, yes this was removed.

**Comment by bcagarwal** [comment]
@nicholaspierson The issue is closed without any comment/ clarification. I appreciate if you can clarify the issue.
