### ISSUE TITLE
Image doesn't match Instructions

### ISSUE THREAD

**Issue by mpstein** [awsdocs/aws-directory-service-admin-guide#5]
Under the "Delegation of Control Wizard," the "Property-specific" checkbox is marked yet the instructions are ambiguous. Guidance would be appreciated.

Step 7 -12

aws-directory-service-admin-guide/doc_source/prereq_connector.md

**Comment by nicholaspierson** [comment]
It's been awhile but I think that Property-specific just shows checked after you click on any Permission that shows up in the list. If that was not your experience, please update the docs via a pull request and I'll merge it in. Thanks!
