### ISSUE TITLE
Connector account username restrictions not documented

### ISSUE THREAD

**Issue by babaker9** [awsdocs/aws-directory-service-admin-guide#6]
The account username that can be specified for the AD connector has AWS restrictions. Most special characters are not allowed. The error message that results when setting up athe AD connector advises the username can only huse alpanumeric characters, underscore, dash and period.

This restriction is not documented for the AD Connector administration or pre-requisites.

Notably, microsoft AD user administration allows creation of usernames with almost no limit on special character usage. Our IS security have a standard of using ! (exclamation) for service accounts. This generated a hard error in the AD Connector setup. AWS documentation does not explain why AWS services apply restrictions  for connection to external systems and services beyond what those same apps/services apply self impose.

**Comment by nicholaspierson** [comment]
Thanks for your comment! I am investigating this further with Program Management. Thanks again for helping us improve our docs! :)

AWS Directory Service
Sr. Tech Writer
Nick Pierson
